### ISSUE TITLE
Glitches: Mega Man x2 Slowdown

### ISSUE THREAD

**Issue by Chronokeys** [SmokeMonsterPacks/Super-NT-Jailbreak#141]
**Behavior:** 
There's significant slowdown on the main menu and some other areas of the game that is not present in real cart. 

**//This issue relates to the super nt implementation of the CX4 chip, and does not occur with real carts.//**

**Steps to Reproduce:**
**New info 2021:** It's very easy to detect the slowdown in the intro cutscene of MMX2, the spinning helmet animation slows down considerably causing the intro music to end where its not supposed to. The helmet has a "coming forth" animation that slowdowns midway. Music ends and the helmet is still on screen, on the real cart the music continues to the next screen and ends with Megaman making his superhero pose. 
Please go to second 0:45 of this video https://www.youtube.com/watch?v=IURT8bhpm2I&t=67s for reference. The difference in speed is very noticeable.

On the main menu scroll up/down through the options to find its very unresponsive, some inputs will not get recognized at all, when choosing an option megaman fires a shot and the screen fades out, this also goes slower. The fight against the sword miniboss also has some slowdown. I've compared this to an actual Rockman x2 cart and you can tell the difference right away.

Firmware: 
JB 6.9

Rom: 
Mega Man X2 (USA).sfc

md5: 
d41d8cd98f00b204e9800998ecf8427e

Stock SNT settings

**Comment by Nigoli** [comment]
I played through the Japanese version had had the problem too.

The late prototype also shares these symptoms. Crystal Snail and the Stage Select as you beat more bosses makes it the most noticeable.

I think that the Cx4 is different than X3’s because that is barely noticeable. X3 was questionable to me with fighting the Sigma Virus and maybe when I fought the wireframe mini boss in Blast Hornet’s stage using the Cross Charge shot. I think X3 needs more testing comparing it’s orignal cartridge.

**Comment by benisjamino** [comment]
I just get the error message, "cannot open dsp file," on Mega Man X2 and X3

**Comment by rtrind** [comment]
> I just get the error message, "cannot open dsp file," on Mega Man X2 and X3

You are probably just missing the special files on the SD card to run DSP roms. Not the error reported on this thread.

**Comment by re4mat** [comment]
Was not able to reproduce the issue on JB7.0.

**Comment by tjanas** [comment]
Please reopen per @re4mat and @Chronokeys

**Comment by Chronokeys** [comment]
Added new info to the OP, the difference should be easier to pinpoint.

**Comment by SmokeMonsterPacks** [comment]
@re4mat reported it's fixed in 7.0. OP is tested with 6.9.

**Comment by re4mat** [comment]
OP and I had a conversation in Discord after the issue was closed and we determined that the issue is actually still present in 7.0. New details were just added to the original post by the OP.

**Comment by Nigoli** [comment]
Have you guys actually tried **playing through the game** to see if the slowdowns that happened to me still exist? It's not just something that happens on the title screen and choosing a selection. It's all the same irregardless of which region.

Even X3 isn't as accurate as a real cartridge here.

**Comment by tjanas** [comment]
@Chronokeys @Nigoli please retest with [JB v7.2](https://github.com/analoguejb/Analogue-Super-Nt-JB). It has been reported as fixed in the change log.

**Comment by Chronokeys** [comment]
It is not fixed, dunno what the guy testing this is thinking or why they claim once again that the issue is fixed, it’s clearly not. Guess it must be a tough one to crack since this the 2nd attempt, 3rd if you count first release.

**Comment by tjanas** [comment]
@Chronokeys if the change log is not correct and this is not fixed, please open an issue at the new GitHub repo for visibility.

**Comment by tjanas** [comment]
https://github.com/analoguejb/Analogue-Super-Nt-JB/issues

**Comment by Chronokeys** [comment]
I apologize, upon further testing it appears the game now runs at the correct speed, there is still some slowdown but apparently rock man x2 and mega man x2 both run the wireframe animation at different speed for some reason, so that's that, issue fixed
