### ISSUE TITLE
Glitches: Top Gear 3000 (PAL, Australia) - (Minor issue) Incorrect colour @ 1 player split screen & after race completion (Track Description screen, random)

### ISSUE THREAD

**Issue by tmagri** [SmokeMonsterPacks/Super-NT-Jailbreak#74]
## Expected behaviour and actual behaviour
Within the race, instead of the colour for the outlier of font and border colour, being black, goes green. (For the first race this occurs when computer Player 2 arrives @ 3/4 on Lap 1 (21 to 22 seconds in roughly)). 
![image](https://user-images.githubusercontent.com/3927466/37337037-4611fd24-2707-11e8-9bee-fdf476c6fb8e.png)

After race completion (sometimes, not frequently), background colour instead of being black the colour goes blue.
![image](https://user-images.githubusercontent.com/3927466/37337086-66d9df9a-2707-11e8-9854-e89f24e855d7.png)

## Steps to reproduce the problem
Once the game is loaded:
	1. CHAMPIONSHIP
	2. 1 PLAYER SPLIT
	3. RACE
	4. Press A to exit TRACK DESCRIPTION (Issue 2, Blue, doesn't happen here)
	5. Go down to EXIT
	6. Race as per usual or stay idle. Either way, when computer Player 2 arrives @ 3/4 on Lap 1 (21 to 22 seconds in roughly), the black outlier of font, and border changes from black to green.
	7. Once the race is complete, and continue pressing A until TRACK DESCRIPTION is shown, it may (or may not) have a blue background instead of black (continue more races until issue occurs). 

## ROM name and hash value

Unable to test ROM dump due to not having facilities to dump the cartridge.
I am unsure of the similarity between what roms that currently available like Top Gear 3000 (EUR).sfc* compared to Australia cartridge (although cartridge ID contains EUR) 

Since Cartridge contains DSP-4 Enhancement, the Jailbreak cannot run the ROM.

From testing Top Gear 3000 (EUR).sfc* on Higan (RetroArch Accuracy), with using dsp4.rom, issues do not occur:

*MD5: 46‌2e‌15‌c0‌18‌c6‌53‌33‌5b‌a6‌34‌d3‌c1‌cd‌06‌c9
SHA1: 777D8732023A300A2C566F2D48BC354E0AA1DA7E

Untested on SD2SNES due to not having the device, this would be a good comparison to observe.

## firmware version and SD card model

- Jailbreak firmware version(s):  all, including latest snt_firmware_verJB6.5, and the official 4.4
- relevant Super Nt settings
	• Hardware: PAL (50Hz)
	• Resolution set at 1080p50Hz (the issue also occurs at 60Hz, outside of scope)
	• Any shader configuration (My preference: No Shader)
	• Any Screen size (My preference: 8x7)
	• Any Buffer mode (My preference: Zero Delay)
- Cartridge ID: SNSP-A3TP-EUR
- Phone Shots / Cartridge Scans
![image](https://user-images.githubusercontent.com/3927466/37338198-d61b23d4-270a-11e8-80c0-f788fbc5eeda.png)
![image](https://user-images.githubusercontent.com/3927466/37337592-e73a1a50-2708-11e8-8e07-ac6c93468f50.png)
![image](https://user-images.githubusercontent.com/3927466/37337626-0092fac6-2709-11e8-973f-817816157a16.png)
![image](https://user-images.githubusercontent.com/3927466/37337666-1bb94f6c-2709-11e8-86c8-846ba077a68c.png)
![image](https://user-images.githubusercontent.com/3927466/37337697-2b6aa9b0-2709-11e8-8060-7475e5035824.png)

**Comment by frederic-mahe** [comment]
@tmagri excellent bug report, thanks! If you can, could you please check whether or not the bug occurs on a genuine Super Nintendo?

**Comment by SmokeMonsterPacks** [comment]
There is only one PAL region ROM, so that is good for others testing via SD2SNES. I just tested TG3K on my Retro Duo Portable via SD2SNES and didn't see it. RDP is not a perfect proxy of real hardware, but I would agree that this looks like a SNT bug.

**Comment by SmokeMonsterPacks** [comment]
RaspberryAlpine on Discord just verified both glitches in the EU ROM via SD2SNES

Settings: 1080p60, PAL

**Comment by tmagri** [comment]
@frederic-mahe Hi, Just to check (although confirmed), the issues are not present on the SNES PAL console. 
![20180314_155715](https://user-images.githubusercontent.com/3927466/37384558-baee8224-27a3-11e8-8300-422c79d71f43.jpg)
![20180314_160115](https://user-images.githubusercontent.com/3927466/37384562-c18c9df0-27a3-11e8-8655-ebacca37d952.jpg)
![20180314_160449](https://user-images.githubusercontent.com/3927466/37384567-c5f6e986-27a3-11e8-8e16-5fc73e72c741.jpg)
![20180314_160554](https://user-images.githubusercontent.com/3927466/37384570-c8953350-27a3-11e8-9ef8-28a8edf4e6fb.jpg)
![20180314_160625](https://user-images.githubusercontent.com/3927466/37384574-ccf44abc-27a3-11e8-8a46-3a5f0ebfd05e.jpg)
![20180314_161021](https://user-images.githubusercontent.com/3927466/37384576-d050a1d8-27a3-11e8-95e5-fce1e22dc118.jpg)

**Comment by SmokeMonsterPacks** [comment]
Kev has a fix for Top Gear 3000, but it won't be in the next official firmware update. He wants to release it in a future release to isolate if its fix causes any new issues.

**Comment by Chronokeys** [comment]
Hey, guess the fix hasn't been implemented yet, just wanted to confirm that this still happens on the latest JB with a real NTSC cart, both the blue background screen and the green border during races.

**Comment by teknomedic** [comment]
Similar bug happens using FXPak Pro with Space being blue when on planet/track selection screen.  Also after several races the text reporting your winnings is garbled (Think in area 3 when it first appeared) .  Perhaps this is a special chip problem.

**Comment by teknomedic** [comment]
Update:  For those that care.  The green border glitch and the blue space background glitches are still happening on the FXPak Pro.  Having re-tested on the Super NT (latest jailbreak) with no cart and using the latest firmware on last revision of the SD2SNES (regular) this no longer happens; however, using the SD2SNES Pro / FXPak Pro the split screen green border and blue screen glitches happen again.  This is using a NTSC/USA ROM from No intro's 2020 updated packages.  If I can ever remember where I put my Original SNES I'll test the SD2SNES and FXPak Pro's on that and update.

**Comment by tjanas** [comment]
@tmagri does this bug still exist with JB v7.0?

**Comment by teknomedic** [comment]
I'll have to test it again... I haven't played it on the Super NT since
getting a MiSTer.  Though I've also seen the same issue on MiSTer.

**Comment by tjanas** [comment]
@teknomedic @Chronokeys can you please re-test your cartridges with the latest official firmware? https://www.analogue.co/support/super-nt/firmware/5.1

**Comment by tmagri** [comment]
@tjanas : I had booted up and updated the firmware of the Super NT, with the Top Gear 3000 game.
Issue still persists.
![image](https://user-images.githubusercontent.com/3927466/236593241-0cc0bba4-1843-4cf6-8822-8bb5a94f4718.png)
![image](https://user-images.githubusercontent.com/3927466/236593254-1ddbe8c1-b1b9-44ed-a56a-3355dfbfa3ac.png)

**Comment by tjanas** [comment]
This is an outstanding issue with [MiSTerFPGA](https://github.com/MiSTer-devel/SNES_MiSTer/issues/290) too.

**Comment by tjanas** [comment]
Per kevtris regarding this game issue: "they do an insane amount of DMAs and it can get DMA-bound. when that happens it can then corrupt the palette"

**Comment by BarbieOnWeed** [comment]
Wasn't all known issues fixed in the new firmware?
It say so on the site.

**Comment by tjanas** [comment]
@BarbieOnWeed more issues are fixed in [JB v7.2](https://github.com/analoguejb/Analogue-Super-Nt-JB), especially those that are JB-specific.

**Comment by BarbieOnWeed** [comment]
I have tested the game from SD on JB v7.2 and it seems fixed! :)

Edit: on SD2SNES both pal and ntsc copy still have the issue, but it works on the MSU1 version.

**Comment by tjanas** [comment]
I have also found that the green border issue is absent when running from SD card but present when running from an sd2snes, with JB v7.2.

**Comment by Chronokeys** [comment]
Issue still present when running the real ntsc cart, got the blue screen after the first race…bummer…
